name: Bug report
description: Report a bug you've found
title: "[bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: oracle_db_version
    attributes:
      label: Oracle Database Version
      description: We only support Oracle Database 12.2 and higher
      options:
        - 12.1 and lower (unsupported)
        - 12.2
        - 18
        - 19
        - 21
    validations:
      required: true
  - type: dropdown
    id: oracle_apex_version
    attributes:
      label: Oracle APEX Version
      description: We only support Oracle APEX 20.1 and higher
      options:
        - 19.2 and lower (unsupported)
        - 20.1
        - 20.2
        - 21.1
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
