name: Bug report
description: Report a bug you've found
title: "[bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: version
    attributes:
      label: Oracle Database Version
      description: > 
        What is your Oracle Database version?
        <small>We only support Oracle Database 12.2 and higher</small>
      options:
        - 12.1 and lower (unsupported)
        - 12.2
        - 18
        - 19
        - 21
    validations:
      required: true
  - type: dropdown
    id: Oracle APEX Version
    attributes:
      label: > 
        What is your Oracle APEX version?
        <small>We only support Oracle APEX 20.1 and higher</small>
      multiple: true
      options:
        - 19.2 and lower
        - 20.1
        - 20.2
        - 21.1
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
